include:
  - notebooks-backend/compose.yaml
  - notes-backend/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.27.0
    ports:
      - 5000:80
    depends_on:
      - notebooks
      - notes