apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

#namespace: dev

namePrefix: dev
nameSuffix: -alpha

labels:
  - pairs:
      project: ecomerce-app
      tier: backend
      env: dev

commonAnnotations:
  team: finance
  maintainer: "finance@ourcompany.org"
  repository: "git-repo"

replicas:
  - name: nginx
    count: 2

configMapGenerator:
  - name: feature-flag-config
    literals:
      - use_db=true
      - expose_metrics=true
      - some_other_feature=true
    options:
      disableNameSuffixHash: true
  - name: db-init-config
    files:
      - db-init.js

secretGenerator:
  - name: local-config
    envs:
      - .env.local
    type: Opaque

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx
      spec:
        template:
          spec:
            containers:
            - name: nginx
              resources:
                requests:
                  memory: '128Mi'
                  cpu: '100m'
                limits:
                  memory: '256Mi'
