apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

#namespace: dev

namePrefix: dev
nameSuffix: -alpha

labels:
  - pairs:
      project: ecomerce-app
      tier: backend
      env: dev

commonAnnotations:
  team: finance
  maintainer: "finance@ourcompany.org"
  repository: "git-repo"

images:
  - name: nginx
    newTag: "1.27.1"

replicas:
  - name: nginx
    count: 2

configMapGenerator:
  - name: feature-flag-config
    literals:
      - use_db=true
      - expose_metrics=true
      - some_other_feature=true
    options:
      disableNameSuffixHash: true
  - name: db-init-config
    files:
      - db-init.js

secretGenerator:
  - name: local-config
    envs:
      - .env.local
    type: Opaque
