apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
  - name: traffic-generator
    image: danieltsonkov/traffic-generator:1.0.0
    args:
      - 'color-api-clusterip/api'
      - '0.5'
