name: notebooks-backend

services:
  notebooks:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    environment:
      - PORT=80
      - DB_URL=mongodb://<user>:<password>@notebooks-db/<db-name>
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
    networks:
      - notebooks-net
  notebooks-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: volume
        source: notebooks-data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    networks:
      - notebooks-net

volumes:
  notebooks-data:

networks:
  notebooks-net: