name: notebooks-backend

services:
  notebooks:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    environment:
      - PORT=80
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
  notebooks-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: volume
        source: notebooks-data
        target: /data/db

volumes:
  notebooks-data: